# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master
pool:
  vmImage: 'ubuntu-latest'

steps:

  - task: UsePythonVersion@0
    displayName: 'Use Python 3.x'

  - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0
    displayName: 'Use Terraform 0.12.24'
    inputs:
      terraformVersion: 0.12.24

  - task: PythonScript@0
    displayName: 'Execute Terraform'
    inputs:
      scriptPath: '$(System.DefaultWorkingDirectory)/_Terraform/terraformexec.py'
      arguments: '--configfile terraform-dev.json --clientSecret $(SPClientSecret) --accessKey $(AccessKeyStorage) --apply'
      workingDirectory: '$(System.DefaultWorkingDirectory)/_Terraform'