# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0
  displayName: 'Install Terraform 0.12.24'
  inputs:
    terraformVersion: 0.12.24

- script: terraform init -backend-config="CHAP07/pipeline/backend.tfvars" "CHAP07/pipeline/"
  displayName: 'Terraform init'

- script: terraform plan -out=outpipeline.tfplan "CHAP07/pipeline/"
  displayName: 'Terraform plan'


- script: terraform apply outpipeline.tfplan -auto-approve
  displayName: 'Terraform apply'